### ISSUE TITLE
Invalid account

### ISSUE THREAD

**Issue by ChinigamiHunter** [tarikhagustia/php-mt5#4]
hi sir,
thanks for you effort.
i get this probleme "Invalid account",

i'm testing with metatrader 5 Demo.

my config is :

$server = "195.201.195.179";
$port = 443;
$login = "5005078968";
$password = "xxxxxx";
$exampleLogin = 5005078968;

$client = new MetaTraderClient($server, $port, $login, $password);
$user = $client->getUser($login);
var_dump($user);

**Comment by tarikhagustia** [comment]
Hi, this library is for Metatrader WEB APi which is need spesial access not using MT5 Demo Account

**Comment by nautonk** [comment]
> Hi, this library is for Metatrader WEB APi which is need spesial access not using MT5 Demo Account

Maaf tanya bro, untuk demo akun apakah MT5 menyediakan API ?

Terima kasih

**Comment by tarikhagustia** [comment]
> > Hi, this library is for Metatrader WEB APi which is need spesial access not using MT5 Demo Account
> 
> Maaf tanya bro, untuk demo akun apakah MT5 menyediakan API ?
> 
> Terima kasih

tidak mas, tapi banyak EA yang bisa access rest api kaya https://github.com/mikha-dev/mt5-rest

**Comment by nautonk** [comment]
> > > Hi, this library is for Metatrader WEB APi which is need spesial access not using MT5 Demo Account
> > 
> > 
> > Maaf tanya bro, untuk demo akun apakah MT5 menyediakan API ?
> > Terima kasih
> 
> tidak mas, tapi banyak EA yang bisa access rest api kaya https://github.com/mikha-dev/mt5-rest

wah pantesan sampek puyeng nyarinya, terima kasih mas saya coba link itu.
